### ISSUE TITLE
Minimum number of contacts for pore-C analysis

### ISSUE THREAD

**Issue by antarikshtyagi** [nanoporetech/pore-c#43]
Hello Eoghan and team,

After multiple rounds of nanopore sequencing we have reached to 50-60 Gbases data for each sample. Pore-C run results in ~250 million contacts each. However downstream processing with juicer results in warning "Warning: Hi-C map is too sparse to find many domains via Arrowhead". 
[slurm-28491.txt](https://github.com/nanoporetech/pore-c/files/5890323/slurm-28491.txt)

Also, similar warnings for HiCCUPS
Could you please suggest the minimum number of contacts required for a reliable pore-C analysis and how much data it would correspond to.

Thanks
Ant

**Comment by eharr** [comment]
See: https://github.com/nanoporetech/Pore-C-Snakemake/issues/17
